services:
  node0:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - MASTER_ADDR=node0
      - MASTER_PORT=48123
    volumes:
      - .:/mnt
    working_dir: /mnt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      distributed-net:
        aliases:
          - node0
    hostname: node0

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - MASTER_ADDR=node0
      - MASTER_PORT=48123
    volumes:
      - .:/mnt
    working_dir: /mnt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      distributed-net:
        aliases:
          - node1
    hostname: node1
    depends_on:
      - node0

networks:
  distributed-net:
    driver: bridge