services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - MASTER_ADDR=node
      - MASTER_PORT=48123
    volumes:
      - .:/mnt
    working_dir: /mnt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      distributed-net:
        aliases:
          - node
    hostname: node

networks:
  distributed-net:
    driver: bridge